use qanda;

CREATE TABLE if not exists Aborts (
	id integer(11) NOT NULL auto_increment PRIMARY KEY,
	accessed_at datetime NOT NULL,
	aborted_clients varchar(11) NOT NULL UNIQUE,
	aborted_connects varchar(11) NOT NULL
) ENGINE = INNODB ;

CREATE TABLE if not exists InnoDBInfo (
	id integer(11) NOT NULL auto_increment PRIMARY KEY,
	accessed_at datetime NOT NULL,
	buffer_pool_dump_status varchar(50) NOT NULL,
	buffer_pool_load_status varchar(50) NOT NULL,
	buffer_pool_pages_data varchar(11) NOT NULL,
	buffer_pool_bytes_data varchar(11) NOT NULL,
	buffer_pool_pages_dirty varchar(11) NOT NULL,
	buffer_pool_bytes_dirty varchar(11) NOT NULL,
	buffer_pool_pages_flushed varchar(11) NOT NULL,
	buffer_pool_pages_free varchar(11) NOT NULL,
	buffer_pool_pages_misc varchar(11) NOT NULL,
	buffer_pool_pages_total varchar(11) NOT NULL,
	buffer_pool_read_ahead_rnd varchar(11) NOT NULL,
	buffer_pool_read_ahead varchar(11) NOT NULL,
	buffer_pool_read_ahead_evicted varchar(11) NOT NULL,
	buffer_pool_read_requests varchar(11) NOT NULL,
	buffer_pool_reads varchar(11) NOT NULL,
	buffer_pool_wait_free varchar(11) NOT NULL,
	buffer_pool_write_requests varchar(11) NOT NULL,
	data_fsyncs varchar(11) NOT NULL,
	data_pending_fsyncs varchar(11) NOT NULL,
	data_pending_reads varchar(11) NOT NULL,
	data_pending_writes varchar(11) NOT NULL,
	data_read varchar(11) NOT NULL,
	data_reads varchar(11) NOT NULL,
	data_writes varchar(11) NOT NULL,
	data_written varchar(11) NOT NULL,
	dblwr_pages_written varchar(11) NOT NULL,
	dblwr_writes varchar(11) NOT NULL,
	have_atomic_builtins varchar(10) NOT NULL,
	log_waits varchar(11) NOT NULL,
	log_write_requests varchar(11) NOT NULL,
	log_writes varchar(11) NOT NULL,
	os_log_fsyncs varchar(11) NOT NULL,
	os_log_pending_fsyncs varchar(11) NOT NULL,
	os_log_pending_writes varchar(11) NOT NULL,
	os_log_written varchar(11) NOT NULL,
	page_size varchar(11) NOT NULL,
	pages_created varchar(11) NOT NULL,
	pages_read varchar(11) NOT NULL,
	pages_written varchar(11) NOT NULL,
	row_lock_current_waits varchar(11) NOT NULL,
	row_lock_time varchar(11) NOT NULL,
	row_lock_time_avg varchar(11) NOT NULL,
	row_lock_time_max varchar(11) NOT NULL,
	row_lock_waits varchar(11) NOT NULL,
	rows_deleted varchar(11) NOT NULL,
	rows_inserted varchar(11) NOT NULL,
	rows_read varchar(11) NOT NULL,
	rows_updated varchar(11) NOT NULL,
	num_open_files varchar(11) NOT NULL,
	truncated_status_writes varchar(11) NOT NULL,
	available_undo_logs varchar(11) NOT NULL
) ENGINE = INNODB ;